# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.

on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

  # Run on every push to the main/master branch
  push:
    branches:
      - main
      - master

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generates the snake
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: emregumusai
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Show the status of the build. Makes it easier for debugging (if there's any issues).
      - name: Show build status
        run: git status

      # Push the changes
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update snake animation
          branch: output
          create_branch: true
          file_pattern: dist/*
